"""Canonical simulated-payment/document/consent text; never model-generated."""
COPY = {
'en':['Demo receipt / itinerary','Demo ticket','DEMO PAYMENT COMPLETED - No real money was charged. No supplier booking was made.','Complete demo pay','Send receipt by email','Email consent recorded. Email delivery is separate from your WhatsApp documents.','Review the email address and confirm to send the receipt:','Email receipt','Please provide the email address for your receipt.'],
'nl':['Demobewijs / reisplan','Demoticket','DEMO-BETALING VOLTOOID - Er is geen echt geld afgeschreven. Er is niet bij een aanbieder geboekt.','Demobetaling afronden','Bewijs per e-mail','Toestemming voor e-mail vastgelegd. E-mailbezorging staat los van je WhatsApp-documenten.','Controleer het e-mailadres en bevestig om het bewijs te versturen:','Bewijs e-mailen','Geef het e-mailadres voor je bewijs.'],
'de':['Demo-Beleg / Reiseplan','Demo-Ticket','DEMO-ZAHLUNG ABGESCHLOSSEN - Kein echtes Geld belastet. Keine Buchung beim Anbieter erfolgt.','Demo-Zahlung beenden','Beleg per E-Mail','E-Mail-Einwilligung erfasst. Der E-Mail-Versand ist von deinen WhatsApp-Dokumenten getrennt.','Prüfe die E-Mail-Adresse und bestätige den Versand:','Beleg senden','Bitte gib die E-Mail-Adresse für deinen Beleg an.'],
'es':['Recibo demo / itinerario','Entrada demo','PAGO DEMO COMPLETADO - No se cobró dinero real. No se hizo ninguna reserva con proveedores.','Completar pago demo','Recibo por correo','Consentimiento de correo registrado. El correo se envía por separado de los documentos de WhatsApp.','Revisa el correo y confirma el envío del recibo:','Enviar recibo','Indica el correo para tu recibo.'],
'pt':['Recibo demo / itinerário','Bilhete demo','PAGAMENTO DEMO CONCLUÍDO - Não foi cobrado dinheiro real. Não foi feita reserva com fornecedores.','Concluir pagamento','Recibo por email','Consentimento de email registado. O email é separado dos documentos de WhatsApp.','Verifique o email e confirme o envio do recibo:','Enviar recibo','Indique o email para o recibo.'],
'pap':['Resibu demo / itinerario','Tiket demo','PAGO DEMO KOMPLETÁ - No a kobra sèn real. No a hasi reservashon serka proveedor.','Kompletá pago demo','Resibu pa email','Konsentimentu pa email registrá. Email ta separá for di bo dokumentonan di WhatsApp.','Kontrolá e adrès di email i konfirmá pa manda e resibu:','Manda resibu','Duna e adrès di email pa bo resibu.'],
}
