FROM sha256:287f3bc3fe755dd9d750ab7a3c8203d69863e0911269ad361a9dc7754e529042
ARG SOURCE_REV
LABEL org.opencontainers.image.revision=$SOURCE_REV
COPY wtyj/agents/social/isluno_hospitality.py /app/agents/social/isluno_hospitality.py
COPY wtyj/agents/social/isluno_conversation_understanding.py /app/agents/social/isluno_conversation_understanding.py
